In [1]:
import os
import pandas as pd
import numpy as np
import quandl
import csv

In [2]:
data = pd.DataFrame()
data = quandl.get("WIKI/AAPL", start_date="1950-01-01", end_date="2018-02-23", api_key='zqxuPnVG5igk65xLKwKQ')

data


Open      High       Low    Close      Volume  Ex-Dividend  \
Date                                                                        
1980-12-12   28.750   28.8700   28.7500   28.750   2093900.0          0.0   
1980-12-15   27.380   27.3800   27.2500   27.250    785200.0          0.0   
1980-12-16   25.370   25.3700   25.2500   25.250    472000.0          0.0   
1980-12-17   25.870   26.0000   25.8700   25.870    385900.0          0.0   
1980-12-18   26.630   26.7500   26.6300   26.630    327900.0          0.0   
1980-12-19   28.250   28.3800   28.2500   28.250    217100.0          0.0   
1980-12-22   29.630   29.7500   29.6300   29.630    166800.0          0.0   
1980-12-23   30.880   31.0000   30.8800   30.880    209600.0          0.0   
1980-12-24   32.500   32.6300   32.5000   32.500    214300.0          0.0   
1980-12-26   35.500   35.6200   35.5000   35.500    248100.0          0.0   
1980-12-29   36.000   36.1300   36.0000   36.000    415900.0          0.0   
1980-12-30   35.250   35.2500   35.1200   35.120    307500.0          0.0   
1980-12-31   34.250   34.2500   34.1300   34.130    159600.0          0.0   
1981-01-02   34.500   34.7500   34.5000   34.500     96700.0          0.0   
1981-01-05   33.870   33.8700   33.7500   33.750    159500.0          0.0   
1981-01-06   32.370   32.3700   32.2500   32.250    201600.0          0.0   
1981-01-07   31.000   31.0000   30.8800   30.880    248600.0          0.0   
1981-01-08   30.370   30.3700   30.2500   30.250    177800.0          0.0   
1981-01-09   31.880   32.0000   31.8800   31.880     96000.0          0.0   
1981-01-12   31.880   31.8800   31.6200   31.620    105800.0          0.0   
1981-01-13   30.630   30.6300   30.5000   30.500    102900.0          0.0   
1981-01-14   30.630   30.7500   30.6300   30.630     63800.0          0.0   
1981-01-15   31.250   31.5000   31.2500   31.250     62800.0          0.0   
1981-01-16   31.120   31.1200   31.0000   31.000     59800.0          0.0   
1981-01-19   32.870   33.0000   32.8700   32.870    185600.0          0.0   
1981-01-20   32.000   32.0000   31.8800   31.880    134300.0          0.0   
1981-01-21   32.500   32.7500   32.5000   32.500     71000.0          0.0   
1981-01-22   32.870   33.1300   32.8700   32.870    158700.0          0.0   
1981-01-23   32.870   33.0000   32.7500   32.750     50100.0          0.0   
1981-01-26   32.370   32.3700   32.2500   32.250    110000.0          0.0   
...             ...       ...       ...      ...         ...          ...   
2018-01-11  174.590  175.4886  174.4900  175.280  17523256.0          0.0   
2018-01-12  176.180  177.3600  175.6500  177.090  25039531.0          0.0   
2018-01-16  177.900  179.3900  176.1400  176.190  29159005.0          0.0   
2018-01-17  176.150  179.2500  175.0700  179.100  32752734.0          0.0   
2018-01-18  179.370  180.1000  178.2500  179.260  30234512.0          0.0   
2018-01-19  178.610  179.5800  177.4100  178.460  30827809.0          0.0   
2018-01-22  177.300  177.7800  176.6016  177.000  26023683.0          0.0   
2018-01-23  177.300  179.4400  176.8200  177.040  31702531.0          0.0   
2018-01-24  177.250  177.3000  173.2000  174.220  50562257.0          0.0   
2018-01-25  174.505  174.9500  170.5300  171.110  39661804.0          0.0   
2018-01-26  172.000  172.0000  170.0600  171.510  37121805.0          0.0   
2018-01-29  170.160  170.1600  167.0700  167.960  48434424.0          0.0   
2018-01-30  165.525  167.3700  164.7000  166.970  45137026.0          0.0   
2018-01-31  166.870  168.4417  166.5000  167.430  30984099.0          0.0   
2018-02-01  167.165  168.6200  166.7600  167.780  38099665.0          0.0   
2018-02-02  166.000  166.8000  160.1000  160.370  85436075.0          0.0   
2018-02-05  159.100  163.8800  156.0000  157.490  66090446.0          0.0   
2018-02-06  154.830  163.7200  154.0000  163.030  66625484.0          0.0   
2018-02-07  163.085  163.4000  159.0685  159.540  50852130.0          0.0   
2018-02-08 

In [3]:
path = str(os.getcwd()) + "/" + "data"
data.to_csv("trainData.csv")

In [4]:
def read_train():
    prices = pd.read_csv("trainData.csv")
    prices = clean(prices)
    return prices

def clean(prices):
    (m, n) = prices.shape

    prices = prices.loc[:, ['Date', 'Open', 'Close']]

    # Add new column "Close Price at the Previous Day" and "Open Price at the Previous Day"
    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-1)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev')

    # Add new column "Close Price at the Day Before" and "Open Price at the Day Before"
    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-2)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev2')

    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-3)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev3')

    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-4)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev4')

    prevColumn = prices.loc[:, ['Open', 'Close']].assign(index = lambda x: x.index-5)
    prevColumn = prevColumn.set_index('index')
    prices = prices.join(prevColumn, rsuffix='Prev5')



    # No need now to save the fifth days data
    prices = prices[:m-5]

    return prices


def write_train(data):
    data.loc[:, ['Date','Open','OpenPrev','ClosePrev','OpenPrev2','ClosePrev2','OpenPrev3','ClosePrev3',
                 'OpenPrev4','ClosePrev4','OpenPrev5','ClosePrev5']].to_csv("trainX.csv", index=False)
    data.loc[:, ['Close']].to_csv( "trainY.csv",index=False)
    
def write_test(data):
    print(year_Y_2017)
    year_2017=data.loc[mask]
    year_2017.loc[:, ['Date','Open','OpenPrev','ClosePrev','OpenPrev2','ClosePrev2','OpenPrev3','ClosePrev3',
                 'OpenPrev4','ClosePrev4','OpenPrev5','ClosePrev5']].to_csv("trainX.csv", index=False)
    year_2017.loc[:, ['Close']].to_csv( "trainY.csv",index=False)
    
 

In [5]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import explained_variance_score

In [6]:
def read_val():
    X = pd.read_csv("trainX.csv", header=0)
    y = pd.read_csv("trainY.csv", header=0)
    X['Date'] = pd.to_datetime(X['Date'], format='%Y-%m-%d')
    return X, y



def plot_trend(x, predict, y, title):
    plt.xticks(rotation=45)
    plt.plot_date(x, y, fmt='b-', xdate=True, ydate=False, label='Real value')
    plt.plot_date(x, predict, fmt='r-', xdate=True, ydate=False, label='Predicted value')
    plt.legend(loc='upper center')
    plt.ylabel('Close prices')
    plt.title(title)
    plt.grid()
    plt.show()


def modify(X, columns):
    columns.append('Date2num')
    returnX = X.loc[:, columns]
    return returnX


def predict_and_plot(X, date):
    m, n = X.shape
    X_test = X.loc[np.floor(m*0.6)+1:]
    X_train = X.loc[:np.floor(m*0.6)]
    
    y_test = y.loc[np.floor(m*0.6)+1:]
    y_train = y.loc[:np.floor(m*0.6)]
    
    date_test = date.loc[np.floor(m*0.6)+1:]
    date_train = date.loc[:np.floor(m*0.6)]
    
    lr = LinearRegression()

    lr.fit(X_train, y_train)

    print('Coefficients: \n', lr.coef_)
    print('Intercept: \n', lr.intercept_)
    pred = lr.predict(X_test)
#     mae = mean_absolute_error(y_test,pred)
    
#     min_data = pred-mae
#     max_data = pred+mae
#     #my_data.append(pred-mae)
#     #print(my_data)
#     data =[{'Min' : min_data, 'Max' : max_data}]
#     min_max_range = pd.DataFrame(data)
#     #min_max_range['Max'] = pred+mae
#     print(min_max_range)
    
    
#     print("Number of variables: %d; Residual sum of squares: %.2f; Variance score: %.5f,Mean absolute error: %.2f"
#           % (n, np.mean((pred - y_test) ** 2), explained_variance_score(y_test, pred),mean_absolute_error(y_test,pred)))
   
    
#     plot_trend(date_train, lr.predict(X_train), y_train, 'Apple')
#     plot_trend(date_test, lr.predict(X_test), y_test, 'Apple')
    
    return lr,pred

    

In [7]:
prices_train=read_train()
write_train(prices_train)

X, y = read_val()

X['Date2num'] = X['Date'].apply(lambda x: mdates.date2num(x))
date = X.loc[:, ['Date']]
del X['Date']

X1 = modify(X, [])
predict_and_plot(X1,date)

Coefficients: 
 [[ 0.00076645]]
Intercept: 
 [-521.22946147]


(LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False),
 array([[ 39.27815053],
        [ 39.27891698],
        [ 39.27968344],
        ..., 
        [ 43.44612591],
        [ 43.44689236],
        [ 43.44765881]]))

In [11]:
#X2 = modify(X, ['Open'])
#lr,close_val=predict_and_plot(X2, date)

X3 = modify(X, ['Open','OpenPrev','ClosePrev'])
lr,close_val=predict_and_plot(X3, date)
X3

Coefficients: 
 [[  4.53114954e-01   5.35639322e-01   1.29750833e-02   3.52903695e-06]]
Intercept: 
 [-2.63869268]


Open  OpenPrev  ClosePrev  Date2num
0      28.750    27.380      27.25  723161.0
1      27.380    25.370      25.25  723164.0
2      25.370    25.870      25.87  723165.0
3      25.870    26.630      26.63  723166.0
4      26.630    28.250      28.25  723167.0
5      28.250    29.630      29.63  723168.0
6      29.630    30.880      30.88  723171.0
7      30.880    32.500      32.50  723172.0
8      32.500    35.500      35.50  723173.0
9      35.500    36.000      36.00  723175.0
10     36.000    35.250      35.12  723178.0
11     35.250    34.250      34.13  723179.0
12     34.250    34.500      34.50  723180.0
13     34.500    33.870      33.75  723182.0
14     33.870    32.370      32.25  723185.0
15     32.370    31.000      30.88  723186.0
16     31.000    30.370      30.25  723187.0
17     30.370    31.880      31.88  723188.0
18     31.880    31.880      31.62  723189.0
19     31.880    30.630      30.50  723192.0
20     30.630    30.630      30.63  723193.0
21     30.630    31.250      31.25  723194.0
22     31.250    31.120      31.00  723195.0
23     31.120    32.870      32.87  723196.0
24     32.870    32.000      31.88  723199.0
25     32.000    32.500      32.50  723200.0
26     32.500    32.870      32.87  723201.0
27     32.870    32.870      32.75  723202.0
28     32.870    32.370      32.25  723203.0
29     32.370    32.250      32.00  723206.0
...       ...       ...        ...       ...
9343  172.540   173.440     175.00  736698.0
9344  173.440   174.350     174.35  736699.0
9345  174.350   174.550     174.33  736702.0
9346  174.550   173.160     174.29  736703.0
9347  173.160   174.590     175.28  736704.0
9348  174.590   176.180     177.09  736705.0
9349  176.180   177.900     176.19  736706.0
9350  177.900   176.150     179.10  736710.0
9351  176.150   179.370     179.26  736711.0
9352  179.370   178.610     178.46  736712.0
9353  178.610   177.300     177.00  736713.0
9354  177.300   177.300     177.04  736716.0
9355  177.300   177.250     174.22  736717.0
9356  177.250   174.505     171.11  736718.0
9357  174.505   172.000     171.51  736719.0
9358  172.000   170.160     167.96  736720.0
9359  170.160   165.525     166.97  736723.0
9360  165.525   166.870     167.43  736724.0
9361  166.870   167.165     167.78  736725.0
9362  167.165   166.000     160.37  736726.0
9363  166.000   159.100     157.49  736727.0
9364  159.100   154.830     163.03  736730.0
9365  154.830   163.085     159.54  736731.0
9366  163.085   160.290     155.32  736732.0
9367  160.290   157.070     155.97  736733.0
9368  157.070   158.500     162.71  736734.0
9369  158.500   161.950     164.34  736737.0
9370  161.950   163.045     167.37  736738.0
9371  163.045   169.790     172.99  736739.0
9372  169.790   172.360     172.43  736740.0

[9373 rows x 4 columns]

In [9]:
daterange = pd.date_range('2018-02-26', '2018-04-30', freq='B')
newDate = pd.DataFrame(data=daterange, columns=['Date'])
newDate = newDate.dropna()
newDate

Date
0  2018-02-26
1  2018-02-27
2  2018-02-28
3  2018-03-01
4  2018-03-02
5  2018-03-05
6  2018-03-06
7  2018-03-07
8  2018-03-08
9  2018-03-09
10 2018-03-12
11 2018-03-13
12 2018-03-14
13 2018-03-15
14 2018-03-16
15 2018-03-19
16 2018-03-20
17 2018-03-21
18 2018-03-22
19 2018-03-23
20 2018-03-26
21 2018-03-27
22 2018-03-28
23 2018-03-29
24 2018-03-30
25 2018-04-02
26 2018-04-03
27 2018-04-04
28 2018-04-05
29 2018-04-06
30 2018-04-09
31 2018-04-10
32 2018-04-11
33 2018-04-12
34 2018-04-13
35 2018-04-16
36 2018-04-17
37 2018-04-18
38 2018-04-19
39 2018-04-20
40 2018-04-23
41 2018-04-24
42 2018-04-25
43 2018-04-26
44 2018-04-27
45 2018-04-30

In [10]:
prevOpen = data.loc[:,['Open']]
prevOpen = prevOpen.iloc[len(prevOpen)-1]
prevClose = close_val.item(len(close_val)-1)
prevOpen = prevOpen.values.item(0)
newX3 = X3
try:
    newX3.drop('Date2num',axis=1,inplace=True)
except:
    print('already dropped')
dummy = pd.DataFrame([[prevClose,prevOpen,prevClose]], columns=['Open','OpenPrev','ClosePrev'])
newX3 = newX3.append(dummy, ignore_index=True)
date = date.append(newDate, ignore_index=True)
for x in range(0,len(newDate)-1):
    print(len(newX3))
    print(len(date))
    lr,close_val = predict_and_plot(newX3, date)
    prevClose = close_val.item(len(close_val)-1)
    prevOpen = newX3.loc[:,['Open']]
    prevOpen = prevOpen.iloc[len(prevOpen)-1]
    prevOpen = prevOpen.values.item(0)
    dummy = pd.DataFrame([[prevClose,prevOpen,prevClose]], columns=['Open','OpenPrev','ClosePrev'])
    newX3 = newX3.append(dummy, ignore_index=True)

newX3

9374
9419
Coefficients: 
 [[ 0.45316599  0.53559317  0.01301275]]
Intercept: 
 [-0.07381775]
9375
9419
Coefficients: 
 [[ 0.45316392  0.53558952  0.01301653]]
Intercept: 
 [-0.07371714]
9376
9419
Coefficients: 
 [[ 0.45316392  0.53558952  0.01301653]]
Intercept: 
 [-0.07371714]
9377
9419
Coefficients: 
 [[ 0.45316359  0.53559292  0.01301061]]
Intercept: 
 [-0.07356921]
9378
9419
Coefficients: 
 [[ 0.45316359  0.53559292  0.01301061]]
Intercept: 
 [-0.07356921]
9379
9419
Coefficients: 
 [[ 0.4531633   0.53559375  0.01301091]]
Intercept: 
 [-0.07361274]
9380
9419
Coefficients: 
 [[ 0.45316477  0.53559574  0.01300839]]
Intercept: 
 [-0.07366091]
9381
9419
Coefficients: 
 [[ 0.45316477  0.53559574  0.01300839]]
Intercept: 
 [-0.07366091]
9382
9419
Coefficients: 
 [[ 0.45316122  0.53559896  0.01300664]]
Intercept: 
 [-0.07355334]
9383
9419
Coefficients: 
 [[ 0.45316122  0.53559896  0.01300664]]
Intercept: 
 [-0.07355334]
9384
9419
Coefficients: 
 [[ 0.45316131  0.53559884  0.01300694]]
Inte

Open    OpenPrev   ClosePrev
0      28.750000   27.380000   27.250000
1      27.380000   25.370000   25.250000
2      25.370000   25.870000   25.870000
3      25.870000   26.630000   26.630000
4      26.630000   28.250000   28.250000
5      28.250000   29.630000   29.630000
6      29.630000   30.880000   30.880000
7      30.880000   32.500000   32.500000
8      32.500000   35.500000   35.500000
9      35.500000   36.000000   36.000000
10     36.000000   35.250000   35.120000
11     35.250000   34.250000   34.130000
12     34.250000   34.500000   34.500000
13     34.500000   33.870000   33.750000
14     33.870000   32.370000   32.250000
15     32.370000   31.000000   30.880000
16     31.000000   30.370000   30.250000
17     30.370000   31.880000   31.880000
18     31.880000   31.880000   31.620000
19     31.880000   30.630000   30.500000
20     30.630000   30.630000   30.630000
21     30.630000   31.250000   31.250000
22     31.250000   31.120000   31.000000
23     31.120000   32.870000   32.870000
24     32.870000   32.000000   31.880000
25     32.000000   32.500000   32.500000
26     32.500000   32.870000   32.870000
27     32.870000   32.870000   32.750000
28     32.870000   32.370000   32.250000
29     32.370000   32.250000   32.000000
...          ...         ...         ...
9389  174.709837  174.556554  174.709837
9390  174.863559  174.709837  174.863559
9391  175.017318  174.863559  175.017318
9392  175.170891  175.017318  175.170891
9393  175.324835  175.170891  175.324835
9394  175.479717  175.324835  175.479717
9395  175.634389  175.479717  175.634389
9396  175.789448  175.634389  175.789448
9397  175.944321  175.789448  175.944321
9398  176.099569  175.944321  176.099569
9399  176.254615  176.099569  176.254615
9400  176.410031  176.254615  176.410031
9401  176.565524  176.410031  176.565524
9402  176.721209  176.565524  176.721209
9403  176.877067  176.721209  176.877067
9404  177.032834  176.877067  177.032834
9405  177.188770  177.032834  177.188770
9406  177.344891  177.188770  177.344891
9407  177.501183  177.344891  177.501183
9408  177.657660  177.501183  177.657660
9409  177.814425  177.657660  177.814425
9410  177.971090  177.814425  177.971090
9411  178.128085  177.971090  178.128085
9412  178.284963  178.128085  178.284963
9413  178.442181  178.284963  178.442181
9414  178.599264  178.442181  178.599264
9415  178.756635  178.599264  178.756635
9416  178.914129  178.756635  178.914129
9417  179.072039  178.914129  179.072039
9418  179.230005  179.072039  179.230005

[9419 rows x 3 columns]

In [13]:
date

Date
0    1980-12-12
1    1980-12-15
2    1980-12-16
3    1980-12-17
4    1980-12-18
5    1980-12-19
6    1980-12-22
7    1980-12-23
8    1980-12-24
9    1980-12-26
10   1980-12-29
11   1980-12-30
12   1980-12-31
13   1981-01-02
14   1981-01-05
15   1981-01-06
16   1981-01-07
17   1981-01-08
18   1981-01-09
19   1981-01-12
20   1981-01-13
21   1981-01-14
22   1981-01-15
23   1981-01-16
24   1981-01-19
25   1981-01-20
26   1981-01-21
27   1981-01-22
28   1981-01-23
29   1981-01-26
...         ...
9343 2018-01-04
9344 2018-01-05
9345 2018-01-08
9346 2018-01-09
9347 2018-01-10
9348 2018-01-11
9349 2018-01-12
9350 2018-01-16
9351 2018-01-17
9352 2018-01-18
9353 2018-01-19
9354 2018-01-22
9355 2018-01-23
9356 2018-01-24
9357 2018-01-25
9358 2018-01-26
9359 2018-01-29
9360 2018-01-30
9361 2018-01-31
9362 2018-02-01
9363 2018-02-02
9364 2018-02-05
9365 2018-02-06
9366 2018-02-07
9367 2018-02-08
9368 2018-02-09
9369 2018-02-12
9370 2018-02-13
9371 2018-02-14
9372 2018-02-15

[9373 rows x 1 columns]